### ISSUE TITLE
가입

### ISSUE THREAD

**Issue by ParkSangSun1** [ko-KR/JOIN#1]
* 지가 하고 싶은 행동: 숨쉬기

-- Best Regards
안녕하세요, 숨 한번 쉬어보겠습니다

**Comment by MCPE-PC** [comment]
@ParkSangSun1, 검토 후 초대하면 다시 안내드리겠습니다.

**Comment by ParkSangSun1** [comment]
> @ParkSangSun1, 검토 후 초대하면 다시 안내드리겠습니다.

네

**Comment by MCPE-PC** [comment]
#1 #2 #3 #4 #5 #6 #7 #8 #9 초대하였습니다.
초대장은 이메일로 전송되지만 브라우저에서 @ko-KR 으로 들어가도 확인 가능합니다.
지가 하고 싶으신 행동들은 빠른 시일 내에 CSV로 만나보실 수 있도록 하겠습니다.

**Comment by ParkSangSun1** [comment]
혹시 소통은 어떻게 하나요?

**Comment by jisungbin** [comment]
이슈로?!

**Comment by sanha9999** [comment]
나는 외국에 소통 있다.
이것은 혹시 신청인가 애프터?
나는 좋다 너의 발언.

**Comment by ParkSangSun1** [comment]
그렇군요

**Comment by sanha9999** [comment]
무엇을 저장? 이 저장소.
난 궁금해 해야할일.

**Comment by MCPE-PC** [comment]
> 혹시 소통은 어떻게 하나요?

@ParkSangSun1 일반적인 오픈 소스 의사소통 방식은 공개 이슈이지만, 비공개 내용에는 GPG 암호화 또는 이메일을 활용하고는 합니다.
카카오톡 단체 채팅방 등 원하시는 플랫폼 있다면 저에게 요청해주시면 됩니다.

c. c. @jisungbin @sanha9999

**Comment by ParkSangSun1** [comment]
카카오톡으로 한 잔 부탁드립니다

**Comment by sunrabbit123** [comment]
아니면 또는. 직접 채팅방을 구현하는것은 어떠한?

**Comment by sanha9999** [comment]
난 모른다 구현.
아직 어리다 실력 나 자신.

**Comment by jisungbin** [comment]
그것은 매우 귀찮은 일.
그냥 있는거 갖다 쓰는게 쵝오.

**Comment by ParkSangSun1** [comment]
까지가 저 친구의 독단적인 의견이구요

**Comment by daeyeong1573** [comment]
인정하는 부분입니다.

**Comment by ParkSangSun1** [comment]
동감.

**Comment by sunrabbit123** [comment]
카카오톡 한잔.

**Comment by sanha9999** [comment]
어떻게 생각해 discord?
카카오톡 외국 없다.

**Comment by MCPE-PC** [comment]
> 아니면 또는. 직접 채팅방을 구현하는것은 어떠한?

@sanha9999  마이너 플랫폼에 대해 이야기해봅시다!
 * Gitter: 조악합니다.
 * Slack: 저희가 회사입니까?
 * 맞춤 제작: 열악합니다.

**Comment by jisungbin** [comment]
깃헙 이슈 달리는거 실시간이였네요 신기
수정된거 바뀌는거 실시간으로 바로 반영되는건 봤는데

**Comment by jisungbin** [comment]
킹갓 텔레그램 어떠심니까

**Comment by sunrabbit123** [comment]
트위터 공계. 그렇다면

**Comment by ckrudals** [comment]
어허어허.. 쉽지않네

**Comment by sanha9999** [comment]
안된다 트위터.
감춘다 나의 비밀.

**Comment by daeyeong1573** [comment]
이것은 무엇?

**Comment by ParkSangSun1** [comment]
텔레그램. 나를 무섭게 한다.
기억난다. 좋지않은 뉴스.

**Comment by daeyeong1573** [comment]
N

**Comment by ckrudals** [comment]
> 안된다 트위터. 감춘다 나의 비밀.

뭘...무엇을?

**Comment by sanha9999** [comment]
보통의 동영상.
그것은 나의 취미.

**Comment by jisungbin** [comment]
텔레그램 좋은데 ㅠ
그 사건은 좀 슬프네요

**Comment by ParkSangSun1** [comment]
외신에도 보고 되었다.
그 현실은.
그리고 난 한국에 실망했다.
이게 현실.

**Comment by daeyeong1573** [comment]
당신은 래퍼인가?
좋다 라임

**Comment by sanha9999** [comment]
카톡 or 디코.
난 원하다 임하고 진심.

**Comment by jisungbin** [comment]
전 다시 공부를 하러 가겠음니다
카톡이 제일 무난할거 같은데, 만약 만드실거면 카톡으로 가시죵 (의견일 뿐입니다!)

**Comment by ParkSangSun1** [comment]
@MCPE-PC Discord 또는 카카오톡 건의합니다

**Comment by daeyeong1573** [comment]
연락처 남겨 놓을길 바람

**Comment by MCPE-PC** [comment]
반말 마려웠다. 그래서 할 것이다.
카카오톡과 디스코드가 옳다.
깃허브 반응 기능으로 대선 진행한다.
 * :+1:: 카카오톡
 * :heart:: 디스코드

**Comment by sunrabbit123** [comment]
못믿는다. 난. 우리를.
오픈 카카오톡. 어떤가.

**Comment by jisungbin** [comment]
카톡 오픈 톡방 가시졍

**Comment by MCPE-PC** [comment]
> 못믿는다. 난. 우리를. 오픈 카카오톡. 어떤가.

@sunrabbit123 열린 카카오톡, 열린 대한민국. 나쁘지 않다.

**Comment by ParkSangSun1** [comment]
좋습니다

**Comment by sunrabbit123** [comment]
오픈마인드로 함께하는 오픈소스는 우리를 오픈시킨다.

**Comment by jisungbin** [comment]
먼저 만든 사람이 임자

한국 조직
https://open.kakao.com/o/gDVWSvQd

**Comment by sanha9999** [comment]
대한민국 보안강국?
우리나라에서는 모른다 오픈.
내것을 지켜라.

**Comment by ParkSangSun1** [comment]
그것은 희망과 열정을 갈망한다.

**Comment by sanha9999** [comment]
오픈채팅으로 가시죠.

**Comment by MCPE-PC** [comment]
**이상의 대화는 새로운 이슈 토픽으로 진행하시기 바랍니다. 이슈를 닫습니다.**
