### ISSUE TITLE
[가입]

### ISSUE THREAD

**Issue by son-daehyeon** [ko-KR/JOIN#14]
수신: @MCPE-PC

 * [x] 나는 자랑스러운 태극기 앞에 자유롭고 정의로운 대한민국의 무궁한 영광을 다하여 충성을 다할 것을 굳게 다짐합니다.
 * [x] 지가 하고 싶은 행동: 나 원한다해 나의 프로필 조직에 태극기. 너희들의 도움이 필요하다해

 * [x] Donghae mulgwa Baekdusani mareugo daldorok~ Haneunimi bouhasa urinara manse~
 * [x] Namsan wie jeo sonamu cheolgabeul dureun~ deut Baram seori bulbyeonhameun uri gisangilse~
 * [x] Gaeul haneul gonghwalhande nopgo gureum eopsi~ Balgeun dareun uri gaseum ilpyeondansimilse~
 * [x] I gisanggwa i mameuro chungseongeul dahayeo~ Goerouna jeulgeouna nara saranghase~
발신:

**Comment by MCPE-PC** [comment]
노력을 칭찬합니다!
