### ISSUE TITLE
가입

### ISSUE THREAD

**Issue by jisungbin** [ko-KR/JOIN#2]
* 지가 하고 싶은 행동: 호흡하기

-- Best Regards
호흡 계속 해보겠습니다.

**Comment by MCPE-PC** [comment]
@jisungbin, 검토 후 초대하면 다시 댓글 드리겠습니다.
#1

**Comment by jisungbin** [comment]
ㅋㅋㅋㅋㅋㅋ 와
제가 스타 한 번 했다고 가입 신청이 갑자기 많이 생겼네요 ㅋㅋㅋ

**Comment by MCPE-PC** [comment]
> ㅋㅋㅋㅋㅋㅋ 와
> 제가 스타 한 번 했다고 가입 신청이 갑자기 많이 생겼네요 ㅋㅋㅋ

@jisungbin 진짜 장난 아닙니다... ㅋㅋㅋㅋㅋㅋ
