### ISSUE TITLE
가입

### ISSUE THREAD

**Issue by sanha9999** [ko-KR/JOIN#3]
* 지가 하고 싶은 행동: 코로 들숨날숨 조지기

-- Best Regards
열심히 들숨날숨 해보겠습니다

**Comment by MCPE-PC** [comment]
@sanha9999, 대체 어디 채팅방에서 오셨습니까? 🤯 (검토 후에 초대 시 #1 에서 안내드리겠습니다)

**Comment by ParkSangSun1** [comment]
> @sanha9999, 대체 어디 채팅방에서 오셨습니까? 🤯 (검토 후에 초대 시 #1 에서 안내드리겠습니다)

저가 데려왔습니다, 잘했죠?

**Comment by MCPE-PC** [comment]
@ParkSangSun1 성빈님은 오래전에 저랑 아는 사이였어서 자바스크립트쪽 방에서 퍼진건가 했는데 아닌가봅니다 ㅋㅋㅋㅋㅋ
주소에 그냥 ko-KR을 쳤더니 여기가 나온 것 뿐이었던 건가요?

**Comment by sanha9999** [comment]
오히려 좋지않습니까?
난 가입하길 원한다 여기.

**Comment by ParkSangSun1** [comment]
@MCPE-PC 성빈님이 스타를 누른게 타임라인에 보여서 궁금해서 들어가봤는데 닉네임이 희귀해서 관심을 가지게 되었습니다 ㅋㅋㅋㅋㅋㅋ

**Comment by jisungbin** [comment]
@MCPE-PC 
> 성빈님은 오래전에 저랑 아는 사이였어서 자바스크립트쪽 방에서 퍼진건가 했는데 아닌가봅니다 ㅋㅋㅋㅋㅋ

오가닉에서 if 팀 얘기 나와서, 맴버분들 둘러보더가 익숙한 이름이 있어서 깃헙 프로필 들어가봤는데 ko-KR 라는 엄청난 조직을 발견해 버렸어요 ㅋㅋ

그래서,, 스타 누르고 가입 신청 나중에 하려고 했다가 금세 하신 분 있길래 저도 따라서 신청...!

**Comment by sanha9999** [comment]
난 좋다 이조직.
원한다 가입 지금.

**Comment by ParkSangSun1** [comment]
@jisungbin ㅋㅋㅋㅋㅋㅋㅋㅋ 이게 맞지요!

**Comment by MCPE-PC** [comment]
> 난 좋다 이조직.
> 원한다 가입 지금.

@sanha9999 무선 마우스 충전만 다 되면 바로  초대해드리겠습니다❤
지금은 저 혼자 있는 이 Organization이 어디에 활용될지도 궁금해지네요

**Comment by ParkSangSun1** [comment]
> > 난 좋다 이조직.
> > 원한다 가입 지금.
> 
> @sanha9999 무선 마우스 충전만 다 되면 바로 초대해드리겠습니다❤ 지금은 저 혼자 있는 이 Organization이 어디에 활용될지도 궁금해지네요

공익을 위해 활용할 생각입니다
