### ISSUE TITLE
원한다. 나는. 가입을. 이 조직에 대한.

### ISSUE THREAD

**Issue by sunrabbit123** [ko-KR/JOIN#9]
* 지가 하고 싶은 행동: 원한다. 난. 가입을.

-- Best Regards
코드를 야무지게 짭니다.
제가 제일 좋아하는 코드는 다음과 같습니다.

```go





```

그 코드는 매우 완벽한 코드입니다.

**Comment by sanha9999** [comment]
좋네요!
나의 마음은 흔들린다 굉장.
너의 code 원더풀하다 매우.

**Comment by MCPE-PC** [comment]
Go 코드의 기본기를 중요하게 여기시나보네요! 몇 분 내로 모두 초대해드리겠습니다~
#1

**Comment by jisungbin** [comment]
ㅋㅋㅋ 화이트스페이스 언어 멋지네요
덕분에 웃고 감니다

**Comment by ParkSangSun1** [comment]
당신의 코드에 나의 마음이 요동친다. 
내 심금을 울린 당신은 나의 사람이다.
당신은 천사입니다.
